Repository graasp/client, pull requests merged in 2024-11, with the labels that each got.

#404 fix: translation strings
  src/components/NotFoundComponent.tsx
  src/components/ProfilePicture/AvatarUploader.tsx
  src/components/ProfilePicture/CropModal.tsx
  src/components/ProfilePicture/useUploadProgress.tsx
  src/components/StorageFiles.tsx
  src/components/main/DeleteMemberDialogContent.tsx
  src/components/main/DeleteMemberSection.tsx
  src/components/main/EditMemberPreferences.tsx
  src/components/main/MainMenu.tsx
  src/components/main/MemberCard.tsx
  src/components/main/MemberPreferences.tsx
  src/components/main/PersonalizationNotificationCard.tsx
  src/config/constants.ts
  src/langs/ar.json
  src/langs/constants.ts
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  src/main.tsx
  src/modules/profile/EditPersonalInformation.tsx
  src/modules/profile/PersonalInformation.tsx
  src/modules/profile/password/CreatePassword.tsx
  src/modules/profile/password/DisplayPassword.tsx
  src/modules/profile/password/EditPassword.tsx
  src/modules/profile/public/EditPublicProfile.tsx
  src/modules/profile/public/PublicProfile.tsx
  src/modules/settings/ExportData.tsx
  src/pages/RequireAuthentication.tsx
  src/routes/account/settings.tsx
  src/routes/account/storage.tsx
  src/routes/email.change.tsx
Labels: chore

#417 fix: remove devtools in prod
  .gitignore
  src/routeTree.gen.ts
  src/routes/__root.tsx
Labels: build, chore

#405 chore(main): release 2.16.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#429 fix: update deployments to use propper install steps
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
Labels: chore

#433 fix: update i18n config
  cypress/e2e/homePage.cy.ts
  cypress/e2e/settings/password.cy.ts
  cypress/e2e/storage.cy.ts
  cypress/tsconfig.json
  package.json
  pnpm-lock.yaml
  public/locales/ar/account.json
  public/locales/ar/messages.json
  public/locales/de/account.json
  public/locales/de/messages.json
  public/locales/en/account.json
  public/locales/en/common.json
  public/locales/en/enums.json
  public/locales/en/landing.json
  public/locales/en/messages.json
  public/locales/es/account.json
  public/locales/fr/account.json
  public/locales/it/account.json
  src/@types/i18next.d.ts
  src/components/NotFoundComponent.tsx
  src/components/header/LeftHeaderWrapper.tsx
  src/components/langs.ts
  src/config/constants.ts
  src/config/i18n.ts
  src/config/messages.ts
  src/config/notifier.ts
  src/langs/constants.ts
  src/main.tsx
  src/modules/account/MainMenu.tsx
  src/modules/account/MemberAvatar.tsx
  src/modules/account/PageWrapper.tsx
  src/modules/account/UserSwitchWrapper.tsx
  src/modules/account/home/MemberCard.tsx
  src/modules/account/home/PlatformSelector.tsx
  src/modules/account/home/TipCard.tsx
  src/modules/account/home/memberPicture/AvatarUploader.tsx
  src/modules/account/home/memberPicture/CropModal.tsx
  src/modules/account/home/memberPicture/useUploadProgress.tsx
  src/modules/account/settings/DeleteMemberDialogContent.tsx
  src/modules/account/settings/DeleteMemberSection.tsx
  src/modules/account/settings/EmailPreferenceSwitch.tsx
  src/modules/account/settings/ExportData.tsx
  src/modules/account/settings/password/CreatePassword.tsx
  src/modules/account/settings/password/EditPassword.tsx
  src/modules/account/settings/password/Password.tsx
  src/modules/account/settings/preferences/EditPreferences.tsx
  src/modules/account/settings/preferences/Preferences.tsx
  src/modules/account/settings/profile/EditPersonalInformation.tsx
  src/modules/account/settings/profile/PersonalInformation.tsx
  src/modules/account/settings/publicProfile/EditPublicProfile.tsx
  src/modules/account/settings/publicProfile/PublicProfile.tsx
  src/modules/account/storage/StorageBar.tsx
  src/modules/account/storage/StorageFiles.tsx
  src/routes/account/settings.tsx
  src/routes/account/storage.tsx
  src/routes/email.change.tsx
  src/routes/index.tsx
  src/routes/login.tsx
  tsconfig.node.json
Labels: feature

#436 feat: add backend proxy
  vite.config.ts
Labels: feature

#438 fix: landing page with small adjustments
  package.json
  public/locales/en/landing.json
  src/modules/landing/footer/Footer.tsx
  src/modules/landing/home/UserStory.tsx
  src/modules/landing/home/UserStorySection.tsx
Labels: improvement

#456 feat: add terms, disclaimer and privacy policy pages
  public/locales/en/landing.json
  src/config/constants.ts
  src/modules/landing/footer/Footer.tsx
  src/modules/landing/home/icons/BeLEARN.tsx
  src/modules/landing/privacyPolicy/layouts.tsx
  src/routeTree.gen.ts
  src/routes/_landing.tsx
  src/routes/_landing/about-us.tsx
  src/routes/_landing/contact-us.tsx
  src/routes/_landing/disclaimer.tsx
  src/routes/_landing/features.tsx
  src/routes/_landing/policy.tsx
  src/routes/_landing/support.tsx
  src/routes/_landing/terms.tsx
  src/routes/disclaimer.tsx
  src/routes/features.tsx
  src/routes/terms.tsx
Labels: feature

#460 fix: move recaptcha to auth layout so we do not track on all pages
  package.json
  pnpm-lock.yaml
  recaptcha.plugin.ts
  src/main.tsx
  src/routes/auth.tsx
  vite.config.ts
Labels: bug

#469 fix: use translation for required validation
  src/modules/account/settings/password/CreatePassword.tsx
  src/modules/account/settings/password/EditPassword.tsx
  src/modules/auth/components/requestPasswordReset/RequestPasswordReset.tsx
  src/modules/auth/components/requestPasswordReset/ResetPassword.tsx
  src/modules/auth/components/signIn/MagicLinkLoginForm.tsx
  src/modules/auth/components/signIn/PasswordLoginForm.tsx
  src/modules/auth/validation.ts
  src/routes/auth/reset-password.tsx
Labels: improvement

#468 fix: update adornemnt and use slotprops
  src/modules/account/settings/password/PasswordField.tsx
  src/modules/account/settings/publicProfile/CustomTextField.tsx
  src/modules/auth/components/common/PasswordInput.tsx
  src/modules/auth/components/common/adornments.tsx
  src/modules/auth/components/register/EmailInput.tsx
  src/modules/auth/components/register/Register.tsx
  src/modules/auth/components/requestPasswordReset/RequestPasswordReset.tsx
  src/modules/auth/components/requestPasswordReset/ResetPassword.tsx
  src/modules/auth/components/signIn/EmailInput.tsx
  src/routes/auth/reset-password.tsx
Labels: bug

#442 chore(main): release 2.17.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#493 feat: add language detector
  .github/workflows/test.yml
  cypress/e2e/player/autoLogin.cy.ts
  cypress/e2e/player/redirections.cy.ts
  package.json
  pnpm-lock.yaml
  public/locales/it/auth.json
  src/AuthContext.tsx
  src/components/langs.ts
  src/config/i18n.ts
  src/main.tsx
  src/modules/auth/components/Footer.tsx
  src/modules/auth/components/Redirection.tsx
  src/modules/player/item/ItemForbiddenScreen.tsx
  src/routes/player/$rootId/$itemId/autoLogin.tsx
Labels: feature

#497 fix: code smells
  src/components/layout/BorderedSection.tsx
  src/components/layout/CenteredContainer.tsx
  src/config/selectors.ts
  src/modules/auth/components/requestPasswordReset/ResetPassword.tsx
  src/modules/player/Chatbox.tsx
  src/modules/player/ItemNavigation.tsx
  src/modules/player/config/selectors.ts
  src/modules/player/errors/FallbackComponent.tsx
  src/modules/player/errors/NetworkErrorAlert.tsx
  src/modules/player/item/FromShortcutButton.tsx
  src/modules/player/item/Item.tsx
  src/modules/player/item/SectionHeader.tsx
  src/modules/player/item/useCollapseAction.tsx
  src/modules/player/navigationIsland/NavigationIsland.tsx
  src/modules/player/navigationIsland/PinnedItemsButton.tsx
  src/modules/player/navigationIsland/PreviousNextButtons.tsx
  src/modules/player/rightPanel/SideContent.tsx
  src/modules/player/tree/LoadingTree.tsx
  src/modules/player/tree/Node.tsx
  src/modules/player/tree/TreeView.tsx
  src/modules/player/ui/CardThumbnail.tsx
  src/modules/player/utils/shuffle.ts
  src/routes/account/storage.tsx
  src/routes/auth/reset-password.tsx
  src/routes/email.change.tsx
  src/routes/player/$rootId/$itemId.tsx
Labels: chore

#498 fix: issues highlighted
  cypress/e2e/account/settings/preferences.cy.ts
  cypress/e2e/player/autoLogin.cy.ts
  cypress/e2e/player/redirections.cy.ts
  public/locales/ar/account.json
  public/locales/de/account.json
  public/locales/en/account.json
  public/locales/en/landing.json
  public/locales/es/account.json
  public/locales/fr/account.json
  public/locales/it/account.json
  src/components/ConstructionTruck.tsx
  src/components/WorkInProgress.tsx
  src/components/ui/ButtonLink.tsx
  src/components/ui/CardActionAreaLink.tsx
  src/components/ui/CustomLink.tsx
  src/components/ui/LanguageSwitch.tsx
  src/components/ui/MainMenuItem.tsx
  src/components/ui/Select.tsx
  src/components/ui/TypographyLink.tsx
  src/modules/account/MainMenu.tsx
  src/modules/account/PageWrapper.tsx
  src/modules/account/home/memberPicture/AvatarUploader.tsx
  src/modules/landing/footer/Footer.tsx
  src/modules/landing/footer/FooterSection.tsx
  src/modules/landing/footer/links.tsx
  src/modules/landing/header/RightHeader.tsx
  src/modules/landing/header/userMenu/MenuItemLink.tsx
  src/modules/player/navigationIsland/customButtons.tsx
  src/modules/player/ui/FolderCard.tsx
  src/routes/account/settings.tsx
  src/routes/player/$rootId/$itemId.tsx
  vite.config.ts
Labels: bug 🪲

#520 fix: reset-query-issue
  cypress/e2e/auth/successContent.cy.ts
  cypress/e2e/player/island.cy.ts
  package.json
  pnpm-lock.yaml
  src/config/selectors.ts
  src/modules/player/navigationIsland/NavigationIsland.tsx
Labels: bug 🪲
