Repository graasp/client, pull requests merged in 2024-06, with the labels that each got.

#244 feat: create read only profile page
  CHANGELOG.md
  cypress/e2e/editMemberProfile.cy.ts
  cypress/e2e/memberProfile.cy.ts
  cypress/fixtures/members.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  src/App.tsx
  src/components/common/RoundedStack.tsx
  src/components/main/DisplayingMemberPublicProfileLinks.tsx
  src/components/main/MainMenu.tsx
  src/components/main/MemberCard.tsx
  src/components/main/MemberPersonalInformation.tsx
  src/components/main/MemberProfileItem.tsx
  src/components/main/MemberPublicProfile.tsx
  src/config/paths.ts
  src/config/selectors.ts
  src/langs/en.json
  src/langs/fr.json
  src/pages/EditMemberPersonalInformation.tsx
  src/pages/EditPublicProfileScreen.tsx
  src/pages/MemberProfileScreen.tsx
Labels: feature

#247 fix: fix avatar size constant
  src/components/main/AvatarUploader.tsx
  src/components/main/MemberCard.tsx
  src/config/constants.ts
Labels: bug

#250 fix: avatar upload size error
  cypress/fixtures/members.ts
  src/components/main/CropModal.tsx
Labels: bug

#259 feat: rename Destructive settings to Settings
  src/App.tsx
  src/components/main/DeleteMemberSection.tsx
  src/components/main/MainMenu.tsx
  src/langs/ar.json
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  src/pages/DestructiveSettingsScreen.tsx
  src/pages/SettingsScreen.tsx
Labels: feature

#263 fix: issue on delete-account-button
  .gitignore
  .vscode/settings.json
  src/components/main/DeleteMemberDialogContent.tsx
  src/components/main/DeleteMemberSection.tsx
Labels: chore

#255 feat: move public profile to profile
  CHANGELOG.md
  cypress/e2e/editMemberPersonalInformation.cy.ts
  cypress/e2e/editMemberPublicProfile.cy.ts
  cypress/e2e/memberProfile.cy.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  src/components/common/TextField.tsx
  src/components/layout/BorderedSection.tsx
  src/components/main/MemberPersonalInformation.tsx
  src/components/main/MemberProfileItem.tsx
  src/components/main/MemberPublicProfile.tsx
  src/components/main/UsernameForm.tsx
  src/config/selectors.ts
  src/pages/EditMemberPersonalInformation.tsx
  src/pages/EditPublicProfileScreen.tsx
  src/pages/MemberProfileScreen.tsx
Labels: feature

#273 chore(main): release 2.10.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
