Repository graasp/client, pull requests merged in 2024-08, with the labels that each got.

#314 feat: add uploaded files in storage interface
  cypress/e2e/storage.cy.ts
  cypress/fixtures/members.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  package.json
  src/components/main/MemberStorageFiles.tsx
  src/config/selectors.ts
  src/langs/en.json
  src/langs/fr.json
  src/main.tsx
  src/pages/StorageScreen.tsx
  yarn.lock
Labels: feature

#320 feat: add data export button in settings page
  cypress/e2e/settings/exportData.cy.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  package.json
  src/config/notifier.ts
  src/config/selectors.ts
  src/langs/en.json
  src/langs/fr.json
  src/modules/settings/ExportData.tsx
  src/pages/SettingsScreen.tsx
  yarn.lock
Labels: feature

#330 fix: remove page size option that exceeds the maximum allowed in storage table
  src/components/main/MemberStorageFiles.tsx
Labels: bug

#332 feat: arabic view - rtl
  package.json
  src/Root.tsx
  yarn.lock
Labels: feature

#333 feat: add 404 page
  cypress/e2e/notFoundPage.cy.ts
  src/App.tsx
  src/config/selectors.ts
  src/langs/en.json
  src/langs/fr.json
  src/pages/HomePage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/PageWrapper.tsx
Labels: feature

#334 fix: update dependencies
  package.json
  src/components/main/MemberPreferences.tsx
  src/utils/clipboard.ts
  yarn.lock
Labels: dependencies
