Repository graasp/client, pull requests merged in 2024-07, with the labels that each got.

#274 chore(main): release 2.10.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#261 feat: add preferences to settings page
  cypress/e2e/editMemberPersonalInformation.cy.ts
  cypress/e2e/editSettings.cy.ts
  cypress/e2e/settingsPage.cy.ts
  cypress/fixtures/members.ts
  src/App.tsx
  src/components/main/EditMemberPreferences.tsx
  src/components/main/EmailPreferenceSwitch.tsx
  src/components/main/LanguageSwitch.tsx
  src/components/main/MemberPreferences.tsx
  src/config/selectors.ts
  src/langs/en.json
  src/langs/fr.json
  src/pages/EditMemberPersonalInformation.tsx
  src/pages/SettingsScreen.tsx
Labels: feature

#275 feat: add email validation page
  cypress/e2e/editMemberPersonalInformation.cy.ts
  cypress/e2e/editSettings.cy.ts
  cypress/e2e/homePage.cy.ts
  cypress/e2e/settingsPage.cy.ts
  cypress/e2e/validateEmailPage.cy.ts
  cypress/support/server.ts
  package.json
  src/App.tsx
  src/Root.tsx
  src/components/common/RoundedStack.tsx
  src/components/layout/BorderedSection.tsx
  src/components/layout/CenteredContainer.tsx
  src/components/layout/ScreenLayout.tsx
  src/components/main/AvatarUploader.tsx
  src/components/main/DeleteMemberDialogContent.tsx
  src/components/main/EditMemberPreferences.tsx
  src/components/main/GraaspIcons.tsx
  src/components/main/MainMenu.tsx
  src/components/main/MemberPreferences.tsx
  src/components/main/MemberPropertyForm.tsx
  src/components/main/PersonalInformation.tsx
  src/config/env.ts
  src/config/hostMapper.ts
  src/config/notifier.ts
  src/config/paths.ts
  src/config/queryClient.ts
  src/config/selectors.ts
  src/langs/en.json
  src/pages/EditMemberPersonalInformation.tsx
  src/pages/EmailChangeValidationScreen.tsx
  src/pages/MemberProfileScreen.tsx
  src/pages/PageWrapper.tsx
  src/pages/PasswordSettingsScreen.tsx
  src/pages/RequireAuthentication.tsx
  src/pages/SettingsScreen.tsx
  src/pages/StorageScreen.tsx
  src/utils/uppy.js
  tsconfig.json
  yarn.lock
Labels: feature

#284 chore(main): release 2.11.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#292 fix: add storage intercept and test
  .eslintrc.json
  .prettierrc
  cypress/cypress.d.ts
  cypress/e2e/homePage.cy.ts
  cypress/e2e/storage.cy.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  cypress/tsconfig.json
  src/config/selectors.ts
  src/pages/StorageScreen.tsx
Labels: tests

#291 feat: create a specification for the get all uploaded files
  docs/storage/uploaded-file-list-specification.md
Labels: documentation

#299 feat: add email from query string in the validate email page
  src/langs/en.json
  src/pages/EmailChangeValidationScreen.tsx
Labels: feature

#307 fix: rename pagination attributes in uploaded files spec
  docs/storage/uploaded-file-list-specification.md
Labels: improvement

#290 chore(main): release 2.12.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
