Repository graasp/client, pull requests merged in 2024-04, with the labels that each got.

#182 fix: allow stacked notifications
  src/Root.tsx
Labels: chore

#187 feat: update main component, favicon and font
  .github/workflows/ci.yml
  .github/workflows/cypress.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  index.html
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/graasp.svg
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/mstile-144x144.png
  public/mstile-150x150.png
  public/mstile-310x150.png
  public/mstile-310x310.png
  public/mstile-70x70.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/App.tsx
  src/components/common/UserSwitchWrapper.tsx
  src/components/context/LayoutContext.tsx
  src/components/context/MainProviders.tsx
  src/components/layout/Header.tsx
  src/components/main/Main.tsx
  src/config/constants.ts
  src/config/env.ts
  src/config/queryClient.ts
  src/config/selectors.ts
  src/env.d.ts
  src/pages/AvatarSettingsScreen.tsx
  src/pages/DestructiveSettingsScreen.tsx
  src/pages/MemberScreen.tsx
  src/pages/PageWrapper.tsx
  src/pages/PasswordSettingsScreen.tsx
  src/pages/PublicProfileScreen.tsx
  src/pages/StorageScreen.tsx
  src/utils/uppy.js
  yarn.lock
Labels: improvement

#180 feat: allow to change username
  cypress/e2e/profile.cy.ts
  cypress/fixtures/members.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  cypress/tsconfig.json
  package.json
  src/components/main/EditingNameField.tsx
  src/components/main/UsernameForm.tsx
  src/config/selectors.ts
  src/langs/ar.json
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  src/pages/MemberScreen.tsx
  tsconfig.json
  yarn.lock
Labels: feature

#195 fix: apply new limits
  cypress/fixtures/members.ts
  package.json
  src/components/main/EditingNameField.tsx
  yarn.lock
Labels: chore

#201 feat: delete delete account from main profile page
  src/pages/MemberScreen.tsx
Labels: feature

#205 fix: use format size from sdk
  package.json
  src/pages/StorageScreen.tsx
  src/utils/filesize.ts
  yarn.lock
Labels: improvement

#208 fix: update dependencies
  package.json
  yarn.lock
Labels: chore
