Repository graasp/client, pull requests merged in 2024-10, with the labels that each got.

#362 fix: deprecate edit member
  cypress/support/commands.ts
  cypress/support/server.ts
  package.json
  src/components/main/EditMemberPreferences.tsx
  src/modules/profile/EditPersonalInformation.tsx
  yarn.lock
Labels: dependencies

#366 fix: remove uppy and use custom hook
  package.json
  src/Root.tsx
  src/components/ProfilePicture/AvatarUploader.tsx
  src/components/ProfilePicture/CropModal.tsx
  src/components/ProfilePicture/useUploadProgress.tsx
  src/components/StorageFiles.tsx
  src/components/main/MemberAvatar.tsx
  src/components/main/MemberCard.tsx
  src/components/main/StatusBar.tsx
  src/langs/en.json
  src/langs/fr.json
  src/pages/PageWrapper.tsx
  src/pages/StorageScreen.tsx
  src/utils/uppy.js
  yarn.lock
Labels: feature

#384 fix: use a single CI workflow
  .github/workflows/ci.yml
  .github/workflows/cypress.yml
Labels: chore, dependencies

#382 feat: add umami plugin in vite config
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  README.md
  umami.plugin.ts
  vite.config.ts
Labels: build, feature

#377 fix: update eslint config
  .eslintignore
  .eslintrc.json
  .vscode/settings.json
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/components/main/DeleteMemberDialogContent.tsx
  src/config/hostMapper.ts
  src/modules/profile/EditPersonalInformation.tsx
  src/pages/StorageScreen.tsx
  src/types/clipboard.ts
  src/utils/currency.ts
  src/utils/image.ts
  vite.config.ts
Labels: build, chore, dependencies

#386 fix: add umami events on password actions
  src/modules/profile/password/CreatePassword.tsx
  src/modules/profile/password/DisplayPassword.tsx
  src/modules/profile/password/EditPassword.tsx
Labels: feature

#363 chore(main): release 2.15.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#388 fix: use package.json defined node version in ci
  .github/workflows/ci.yml
Labels: chore, ci

#389 chore(main): release 2.15.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#391 chore(main): release 2.15.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#408 fix: updated lang is not shown in preferences when switching lang
  cypress/e2e/settings/preferences.cy.ts
  src/components/main/EditMemberPreferences.tsx
Labels: bug

#409 fix: update deps
  package.json
  pnpm-lock.yaml
Labels: dependencies

#411 fix: use the script from cloud and send to our own
  public/umami.js
  umami.plugin.ts
Labels: bug
