Repository graasp/client, pull requests merged in 2025-02, with the labels that each got.

#815 chore(main): release 2.19.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#844 feat: add settings in member drop down
  src/locales/en/common.json
  src/ui/UserSwitch/UserSwitchWrapper.stories.tsx
  src/ui/UserSwitch/UserSwitchWrapper.tsx
Labels: feature

#853 feat: add accessible items on home page
  .github/workflows/test.yml
  cypress/e2e/home/home.cy.ts
  src/modules/account/home/recentItems/RecentItems.tsx
  src/modules/builder/components/pages/BuilderPageLayout.tsx
  src/routes/_memberOnly/home.tsx
  src/ui/Main/Main.tsx
Labels: feature

#862 fix: overflow issue in new item modal
  src/modules/builder/components/item/edit/EditModal.tsx
  src/modules/builder/components/item/header/ItemHeaderActions.tsx
  src/modules/builder/components/main/ItemMenuContent.tsx
  src/modules/builder/components/main/NewItemModal.tsx
Labels: fix

#871 feat: add bookmarks in home
  cypress/e2e/account/homePage.cy.ts
  cypress/e2e/home/home.cy.ts
  src/components/ui/ButtonLink.tsx
  src/modules/account/home/recentItems/DisplayItems.tsx
  src/modules/account/home/recentItems/RecentItems.tsx
  src/modules/analytics/PageWrapper.tsx
  src/modules/auth/components/register/Register.tsx
  src/modules/builder/components/item/publish/ItemPublishTab.tsx
  src/modules/home/MemberCard.tsx
  src/modules/home/bookmarks/BookmarkedItems.tsx
  src/modules/home/bookmarks/ItemCard.tsx
  src/modules/home/memberAnalytics/MemberActionsChart.tsx
  src/modules/home/memberAnalytics/MemberGeneralStatisticsCards.tsx
  src/modules/home/memberAnalytics/OwnAnalytics.tsx
  src/modules/home/memberPicture/AvatarUploader.tsx
  src/modules/home/memberPicture/useUploadProgress.tsx
  src/modules/player/common/ItemCard.tsx
  src/modules/player/common/ItemThumbnail.tsx
  src/routes/_memberOnly/account/settings.tsx
  src/routes/_memberOnly/account/stats.tsx
  src/routes/_memberOnly/home.tsx
  src/routes/auth.tsx
  src/routes/builder/_layout.tsx
  src/routes/builder/items/$itemId.tsx
  src/routes/builder/items/$itemId/_itemPage/settings.tsx
  src/routes/builder/items/$itemId/_itemPage/share.tsx
  src/routes/builder/items/$itemId/index.tsx
  src/ui/Main/HomeHeaderLink.tsx
Labels: feature

#913 feat: add new supporters and refactor to add links to project websites
  public/projects/BeLEARN.webp
  public/projects/sdc.webp
  public/projects/swissuniversities.webp
  src/modules/landing/home/TitleSection.tsx
  src/modules/landing/home/icons/BeLEARN.tsx
  src/modules/landing/home/icons/EPFL.tsx
  src/modules/landing/home/icons/EdTech.tsx
  src/modules/landing/home/icons/GoLab.tsx
  src/modules/landing/home/supporterIcons.tsx
Labels: feature

#918 fix: change profile to home in user menu popup
  src/components/ui/HeaderRightContent.tsx
  src/locales/en/common.json
  src/ui/UserPopupMenu.stories.tsx
  src/ui/UserPopupMenu.tsx
Labels: fix

#916 fix: add limit on bookmarks shown
  src/locales/en/home.json
  src/modules/home/bookmarks/BookmarkCard.tsx
  src/modules/home/bookmarks/BookmarkedItems.tsx
Labels: fix

#849 chore(main): release 2.20.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#942 chore(main): release 2.21.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
