Repository graasp/client, pull requests merged in 2025-01, with the labels that each got.

#570 feat: update landing page images with our own
  public/illustration/features.webp
  public/illustration/group-work.webp
  public/illustration/landing.webp
  public/illustration/teacher-red.webp
  public/illustration/teacher.webp
  public/illustration/team.webp
  src/components/ui/StyledImages.tsx
  src/locales/fr/landing.json
  src/modules/landing/aboutUs/TitleSection.tsx
  src/modules/landing/features/TitleSection.tsx
  src/modules/landing/home/TitleSection.tsx
  src/modules/landing/home/UserStory.tsx
  src/modules/landing/home/UserStorySection.tsx
Labels: feature, I:Landing

#577 fix: link props with tanstack router update
  package.json
  pnpm-lock.yaml
  src/modules/analytics/PageWrapper.tsx
  src/modules/analytics/config/type.ts
  src/modules/analytics/context/MyAnalyticsDateRangeContext.tsx
  src/modules/analytics/utils.ts
  src/modules/landing/features/PlatformOverviewSection.tsx
  src/modules/landing/features/graaspFeature/GraaspFeature.tsx
  src/modules/landing/home/UserTestimoniesSection.tsx
  src/modules/landing/support/NeedHelp.tsx
Labels: dependencies

#591 feat: add navigator back in analytics
  package.json
  pnpm-lock.yaml
  src/components/ui/MenuItemLink.tsx
  src/components/ui/Navigator/CurrentItemNavigation.tsx
  src/components/ui/Navigator/ExtraItemsMenu.tsx
  src/components/ui/Navigator/ExtraItemsNavigation.tsx
  src/components/ui/Navigator/HomeMenu.tsx
  src/components/ui/Navigator/ItemMenu.tsx
  src/components/ui/Navigator/Navigator.tsx
  src/components/ui/Navigator/ParentsNavigation.tsx
  src/components/ui/Navigator/common/CenterAlignWrapper.tsx
  src/components/ui/Navigator/common/constants.ts
  src/modules/analytics/Navigator.tsx
  src/routes/analytics/items/$itemId.lazy.tsx
Labels: feature

#593 fix: social links to use react hook form
  cypress/e2e/account/settings/publicProfile.cy.ts
  cypress/fixtures/members.ts
  cypress/support/commands.ts
  src/components/layout/BorderedSection.tsx
  src/config/selectors.ts
  src/locales/en/account.json
  src/modules/account/settings/password/Password.tsx
  src/modules/account/settings/preferences/Preferences.tsx
  src/modules/account/settings/profile/PersonalInformation.tsx
  src/modules/account/settings/publicProfile/EditPublicProfile.tsx
  src/modules/account/settings/publicProfile/PublicProfile.tsx
Labels: refactor

#596 fix: platform switch in analytics
  src/modules/analytics/PageWrapper.tsx
  src/routeTree.gen.ts
  src/routes/analytics/index.tsx
  src/routes/analytics/items/$itemId.tsx
Labels: improvement

#609 chore(main): release 2.19.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#739 fix: map view
  package.json
  pnpm-lock.yaml
  src/components/ConstructionTruck.tsx
  src/components/NotFoundComponent.tsx
  src/components/WorkInProgress.tsx
  src/components/chatbox/Chatbox/Chatbox.tsx
  src/components/chatbox/Chatbox/Message.tsx
  src/components/chatbox/Chatbox/MessageActions.tsx
  src/components/chatbox/Chatbox/MessageBody.tsx
  src/components/ui/ButtonLink.tsx
  src/components/ui/CardActionAreaLink.tsx
  src/components/ui/CustomLink.tsx
  src/components/ui/MainMenuItem.tsx
  src/components/ui/MenuItemLink.tsx
  src/components/ui/TypographyLink.tsx
  src/main.tsx
  src/modules/account/settings/publicProfile/CustomTextField.tsx
  src/modules/builder/components/item/FolderContent.tsx
  src/modules/builder/components/item/MapView.tsx
  src/modules/builder/components/item/header/Actions.tsx
  src/modules/builder/components/item/settings/ThumbnailSetting.tsx
  src/modules/builder/components/item/sharing/shortLink/ShortLinkMenu.tsx
  src/modules/builder/components/map/DesktopMap.tsx
  src/modules/builder/components/thumbnails/ThumbnailUploader.tsx
  src/modules/builder/map/components/GeolocationPicker/GeolocationPicker.tsx
  src/modules/builder/map/components/Map.stories.tsx
  src/modules/builder/map/components/Map.tsx
  src/modules/builder/map/components/map/CountryContent.tsx
  src/modules/builder/map/components/map/MapContent.tsx
  src/modules/builder/map/components/topbar/MobileTopBar.tsx
  src/modules/builder/map/components/topbar/Search.tsx
  src/modules/builder/map/components/topbar/TopBar.tsx
  src/modules/landing/Platforms/PlatformColorSurface.tsx
  src/modules/landing/features/BlogSection.tsx
  src/modules/landing/footer/links.tsx
  src/modules/landing/header/RightHeader.stories.tsx
  src/modules/landing/header/userMenu/MenuItemLink.tsx
  src/modules/player/navigationIsland/customButtons.tsx
  src/modules/player/ui/FolderCard.tsx
  src/routes/__root.tsx
  src/routes/builder/items/$itemId.tsx
  src/ui/Navigation/HomeMenu.tsx
  src/ui/PlatformSwitch/PlatformSwitch.tsx
  src/ui/draggable/InBetween.tsx
  src/ui/theme.ts
  src/ui/upload/FileDropper/FileDropper.tsx
Labels: dependencies, I:Builder

#741 fix: analytics navigator arrow is miss-aligned
  src/components/ui/Navigator/CurrentItemNavigation.tsx
  src/components/ui/Navigator/ParentsNavigation.tsx
  src/modules/analytics/Navigator.tsx
Labels: I:Analytics

#756 fix: tsc compilation time
  .github/workflows/deploy-prod.yml
  .gitignore
  src/modules/builder/components/item/FolderContent.tsx
  src/modules/builder/components/pages/BookmarkedItemsScreen.tsx
  src/modules/builder/components/pages/PublishedItemsScreen.tsx
  src/modules/builder/components/pages/home/HomeScreenContent.tsx
  src/modules/builder/components/table/SortingSelect.tsx
  src/modules/builder/components/table/useSorting.tsx
  src/ui/Sidebar/Sidebar.stories.tsx
  src/ui/Sidebar/Sidebar.tsx
  src/ui/theme.ts
  tsconfig.app.json
Labels: Performance

#776 fix: map responsive crash because context is not present
  src/modules/builder/map/components/map/InitialSetup.tsx
  src/modules/builder/map/components/map/ItemsMarkers.tsx
  src/modules/builder/map/components/topbar/MobileTopBar.tsx
  src/modules/builder/map/components/topbar/TopBar.tsx
Labels: I:Map

#740 fix: public profile visibility not updating
  src/modules/account/settings/publicProfile/EditPublicProfile.tsx
  src/modules/account/settings/publicProfile/PublicProfile.tsx
Labels: I:Account

#730 chore(main): release 2.19.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#804 chore(main): release 2.19.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#806 chore(main): release 2.19.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#814 chore(main): release 2.19.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending
