Repository graasp/client, pull requests merged in 2025-05, with the labels that each got.

#990 chore(main): release 2.25.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#992 chore(main): release 2.25.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#993 fix: update for new sdk version
  package.json
  pnpm-lock.yaml
  src/modules/builder/components/input/MultiSelectTagChipInput.tsx
  src/modules/builder/components/item/publish/customizedTags/useTagsManager.tsx
  src/query/api/search.ts
  src/query/keys.ts
  src/query/tag/api.ts
  src/query/tag/hooks.ts
  src/query/tag/keys.ts
  src/query/tag/routes.ts
Labels: dependencies

#997 feat: complete contact page
  src/locales/en/landing.json
  src/modules/landing/aboutUs/ContactSection.tsx
  src/modules/landing/footer/Footer.tsx
  src/routes/_landing/about-us.tsx
  src/routes/_landing/contact-us.tsx
Labels: feature, I:Landing
